on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  collect-github-metrics:
    name: Collect GitHub Metrics
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          databranch: metrics
          ghtoken: ${{ secrets.ghrs_github_api_token }}
